# Generated by Django 6.0.5 on 2026-06-03 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comment_parent_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
