# Generated by Django 6.0.5 on 2026-06-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('vin', models.CharField(blank=True, max_length=17, null=True, verbose_name='VIN номер')),
                ('license_plate', models.CharField(blank=True, max_length=20, null=True, verbose_name='Госномер')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Цвет')),
                ('engine_volume', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Объём двигателя (л)')),
                ('horsepower', models.IntegerField(blank=True, null=True, verbose_name='Мощность (л.с.)')),
                ('transmission', models.CharField(blank=True, choices=[('manual', 'Механика'), ('automatic', 'Автомат'), ('robot', 'Робот'), ('cvt', 'Вариатор')], max_length=20, null=True, verbose_name='Коробка передач')),
                ('drive', models.CharField(blank=True, choices=[('front', 'Передний'), ('rear', 'Задний'), ('full', 'Полный')], max_length=20, null=True, verbose_name='Привод')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Фото автомобиля')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название марки')),
            ],
            options={
                'verbose_name': 'Марка автомобиля',
                'verbose_name_plural': 'Марки автомобилей',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название модели')),
            ],
            options={
                'verbose_name': 'Модель автомобиля',
                'verbose_name_plural': 'Модели автомобилей',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000, verbose_name='Текст отзыва')),
                ('rating', models.IntegerField(choices=[(1, '★ 1'), (2, '★★ 2'), (3, '★★★ 3'), (4, '★★★★ 4'), (5, '★★★★★ 5')], default=5, verbose_name='Оценка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Отзыв об автомобиле',
                'verbose_name_plural': 'Отзывы об автомобилях',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Комментарий к отзыву',
                'verbose_name_plural': 'Комментарии к отзывам',
                'ordering': ['created_at'],
            },
        ),
    ]
