# Generated by Django 6.0.5 on 2026-06-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='acceleration',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Разгон 0-100 км/ч (сек)'),
        ),
        migrations.AddField(
            model_name='car',
            name='body_type',
            field=models.CharField(blank=True, choices=[('sedan', 'Седан'), ('hatchback', 'Хэтчбек'), ('suv', 'Внедорожник/SUV'), ('wagon', 'Универсал'), ('coupe', 'Купе'), ('convertible', 'Кабриолет'), ('minivan', 'Минивэн'), ('pickup', 'Пикап')], max_length=50, null=True, verbose_name='Тип кузова'),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_consumption',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Расход топлива (л/100 км)'),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('petrol', 'Бензин'), ('diesel', 'Дизель'), ('electric', 'Электричество'), ('hybrid', 'Гибрид'), ('plug_in_hybrid', 'Подзаряжаемый гибрид')], max_length=30, null=True, verbose_name='Тип топлива'),
        ),
        migrations.AddField(
            model_name='car',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Высота (мм)'),
        ),
        migrations.AddField(
            model_name='car',
            name='length',
            field=models.IntegerField(blank=True, null=True, verbose_name='Длина (мм)'),
        ),
        migrations.AddField(
            model_name='car',
            name='top_speed',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимальная скорость (км/ч)'),
        ),
        migrations.AddField(
            model_name='car',
            name='trunk_volume',
            field=models.IntegerField(blank=True, null=True, verbose_name='Объём багажника (л)'),
        ),
        migrations.AddField(
            model_name='car',
            name='weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='Снаряжённая масса (кг)'),
        ),
        migrations.AddField(
            model_name='car',
            name='width',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ширина (мм)'),
        ),
    ]
